name: CI
on:
  pull_request:
jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: devblackops/github-action-psscriptanalyzer@master
        with:
          settingsPath: .vscode/PSScriptAnalyzerSettings.psd1
          sendComment: false
