name: CI
on:
  pull_request:
   types: 
     labeled
     -name PSSA 
jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        settingsPath: .vscode/PSScriptAnalyzerSettings.psd1
